### ISSUE TITLE
Load balancing JetStream consumers

### ISSUE THREAD

**Issue by alexy4744** [nats-io/nats.js#432]
Hello, I am currently using JetStream and I want to know if it's possible to load balance my consumer, similar to specifying a queue group name in normal NATS. Right now, I have 2 instances of my application running, and each time a producer publishes a message, both instances of my application receive it (both using the same push consumer with a durable name). What I am looking for is a behavior similar to queue groups, where only one of the two instances receives the message.

I was told that this is possible in the nats.go library by subscribing to the stream using `js.QueueSubscribe`, however, I cannot seem to find this documented with nats.js. Can someone point me in the right direction? Thanks.

**Comment by derekcollison** [comment]
Yes you have two options. 

1. Create a pull consumer and have as many applications as you want issue pull requests to get the next message.
2. Create a push consumer and bind to the delivery subject with a normal NATS queue subscriber.

**Comment by alexy4744** [comment]
Thanks, I implemented the second option and it works perfectly. For anyone who finds this issue in the future and also wants to implement a load-balanced push consumer, here is a snippet of my approach:

```ts
import { toJsMsg } from "nats/lib/nats-base-client/jsmsg";

const sub = nc.subscribe("my-delivery-subject", {
  queue: "my-queue-group"
});

(async () => {
  for await (const msg of sub) {
    // Must convert to JsMsg to access ack, nak, etc... methods
    const jsMsg = toJsMsg(msg);

    jsMsg.ack();
  }
})();
```

**Comment by derekcollison** [comment]
I am not super familiar with the JetStream interface in our javascript client, but in the Go client you create a context and do a normal subscribe, and that subscribe will match and bind to an existing consumer or create one if it does not exist. So in the Go client you just have each client do a js.QueueSubscribe("foo", cb, ...) and the first creates a push based consumer (ephemeral or durable) and the subsequent ones just bind to it.

**Comment by aricart** [comment]
The `queue` option is not exposed by the jetstream subscribe. (PR here: https://github.com/nats-io/nats.deno/pull/162).
@derekcollison As for ephemeral consumer matching, this will require a different PR. Still not quite sure how that is useful.

**Comment by derekcollison** [comment]
Let's discuss bringing the js and deno clients more in line with the reference Go client.

**Comment by csombok** [comment]
We are facing the same limitation and for us the only viable options is using the push based subscriber with STAN. 
Are there any ETA for merging this PR: https://github.com/nats-io/nats.deno/pull/162?
As an alternative workaround we can use [patch-package](https://www.npmjs.com/package/patch-package) to have the fix as a patch in node_modules as a temporary solution.

**Comment by aricart** [comment]
@csombok I have released nats v2.0.8 which exposes the queue option.

**Comment by csombok** [comment]
@aricart Thanks a lot for the super quick reaction with the new release
